#!/bin/bash

gcc -c ../lib/common/lib-string.c -o ../bin/lib/common/lib-string.o
gcc zmq-sub.c -lzmq -ljson-c ../bin/lib/common/lib-string.o -o sub.ignore
gcc zmq-pub.c -lzmq -ljson-c ../bin/lib/common/lib-string.o -o pub.ignore

./sub.ignore